events {}

http {
  upstream account_service { server account-service:3001; }
  upstream transaction_service { server transaction-service:3002; }
  upstream ledger_service { server ledger-service:3003; }
  upstream fx_service { server fx-service:3004; }
  upstream payroll_service { server payroll-service:3005; }
  upstream admin_service { server admin-service:3006; }

  server {
    listen 80;

    location /healthz { return 200 'ok'; }

    location /api/accounts/ {
      proxy_pass http://account_service/;
    }

    location /api/transfers {
      proxy_pass http://transaction_service/transfers;
    }

    location /api/transfers/international {
      proxy_pass http://transaction_service/transfers/international;
    }

    location /api/fx/ {
      proxy_pass http://fx_service/;
    }

    location /api/payroll/ {
      proxy_pass http://payroll_service/;
    }

    location /api/admin/ {
      proxy_pass http://admin_service/;
    }
  }
}
